import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import "./globals.css";
import QueryProvider from "@/providers/queryClient";
import Header from "@/components/ui/sections/header";
import Footer from "@/components/ui/sections/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${poppins.variable}  antialiased bg-cover bg-center bg-no-repeat bg-fixed`}
        style={{
          backgroundImage: "url('/images/OnboardingBG.webp')",
        }}
      >
        <ThemeProvider>
          <QueryProvider>
            <Header />
            {children}
            <Footer />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
